name: Pipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: cmb84scd/python-action@v1
    - run: |
        sudo systemctl start postgresql.service
        sudo -u postgres psql -l

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: cmb84scd/python-action@v1
  #   - run: just lint

  # bandit:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: cmb84scd/python-action@v1
  #   - run: just bandit

  # safety:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: cmb84scd/python-action@v1
  #   - uses: pyupio/safety-action@v1
  #     with:
  #       api-key: ${{ secrets.SAFETY_API_KEY }}
