name: Pipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    uses: ./.github/workflows/python.yml
    with:
      task: lint

  bandit:
    uses: ./.github/workflows/python.yml
    with:
      task: bandit

  safety:
    uses: ./.github/workflows/python.yml
    with:
      task: safety
      api-key: ${{ secrets.SAFETY_API_KEY }}
