name: Pipeline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    uses: ./.github/workflows/python.yml
    with:
      task: lint

  bandit:
    uses: ./.github/workflows/python.yml
    with:
      task: bandit

  safety:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'
    - uses: abatilo/actions-poetry@v3
      with:
        poetry-version: '1.8.3'
    - uses: extractions/setup-just@v2
    - name: install dependencies
      run: just install
    - uses: pyupio/safety-action@v1
      with:
        api-key: ${{ secrets.SAFETY_API_KEY }}
