name: 'Python'

on:
  workflow_call:
    inputs:
      task:
        required: false
        type: string

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'
    - uses: abatilo/actions-poetry@v3
      with:
        poetry-version: '1.8.3'
    - uses: extractions/setup-just@v2
    - name: install dependencies
      run: just install
    - run: just ${{ inputs.task }}
