name: 'Python'

# on:
#   workflow_call:
#     inputs:
#       task:
#         required: true
#         type: string
#     secrets:
#       apiKey:
#         required: false

# jobs:
#   python:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
runs:
  using: 'composite'
  steps:
  - uses: abatilo/actions-poetry@v3
    with:
      poetry-version: '1.8.3'
  - uses: actions/setup-python@v5
    with:
      python-version: '3.12'
      cache: 'poetry'
  - uses: extractions/setup-just@v2
  - name: install dependencies
    run: just install
  # - if: inputs.task == 'safety'
  #   uses: pyupio/safety-action@v1
  #   with:
  #     api-key: ${{ secrets.apiKey }}
  # - if: inputs.task != 'safety'
  #   run: just ${{ inputs.task }}
