name: 'Python'

on:
  workflow_call:
    inputs:
      task:
        required: true
        type: string

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: abatilo/actions-poetry@v3
      with:
        poetry-version: '1.8.3'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'
    - uses: extractions/setup-just@v2
    - name: install dependencies
      run: just install
    - if: ["${{ inputs.task }}" == "safety"]
      run: echo "in safety if. Return- ${{inputs.task}}"
      # uses: pyupio/safety-action@v1
      # with:
      #   api-key: ${{ secrets.SAFETY_API_KEY }}
    - if: ${{ inputs.task }} != "safety"
      run: echo "in non safety if. Return- ${{inputs.task}}"
      # run: just ${{ inputs.task }}
